package main

import (
	"fmt"
	"os"
	"path/filepath"
)

// opencodeAdapter wires local-harness mode into opencode via a generated plugin
// (.opencode/plugins/paddock.js, auto-loaded at startup). The plugin's
// tool.execute.before hook rewrites the bash tool's command to run in the
// sandbox via `paddock exec`, throws on the native webfetch tool (unless web
// tools are allowed), and runs paddock's neutral session-start on load so the
// sandbox and sync are up.
type opencodeAdapter struct{}

func (opencodeAdapter) name() string { return "opencode" }

func (opencodeAdapter) detect(dir string) bool {
	for _, p := range []string{".opencode", "opencode.json", "opencode.jsonc"} {
		if _, err := os.Stat(filepath.Join(dir, p)); err == nil {
			return true
		}
	}
	return false
}

func (opencodeAdapter) install(o installOpts) error {
	dir := filepath.Join(".opencode", "plugins")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	path := filepath.Join(dir, "paddock.js")
	if err := os.WriteFile(path, []byte(opencodePlugin(o.allowWeb)), 0o644); err != nil {
		return err
	}
	fmt.Printf("installed the opencode plugin in %s\n", path)
	return nil
}

// opencodePlugin renders the opencode plugin source. denyWeb=true adds the
// webfetch block. The plugin reads the bound session id from .paddock/session at
// call time, so it tracks whatever session paddock provisions/reuses.
func opencodePlugin(allowWeb bool) string {
	webBlock := ""
	if !allowWeb {
		webBlock = `if (input.tool === "webfetch") {
        throw new Error(
          "paddock: webfetch is disabled in local-harness mode — it runs locally and bypasses the governed sandbox egress. Use a shell command (curl/wget) so it runs, allowlisted and audited, in the sandbox."
        );
      }
      `
	}
	return `// paddock local-harness plugin for opencode.
// Generated by ` + "`paddock init --agent opencode`" + ` — do not edit; re-run init to update.
// Redirects the bash tool into the paddock sandbox and ensures the sandbox +
// workspace sync are up. paddock (the CLI) must be on your PATH.
import { readFileSync } from "node:fs";
import { join } from "node:path";

export const paddock = async ({ $, directory }) => {
  // Ensure this directory's sandbox and two-way sync are running. Idempotent:
  // reuses an existing session, or provisions one on first start.
  try {
    await $` + "`paddock hook-session-start`" + `;
  } catch (e) {
    // non-fatal: bash still redirects once a session exists
  }

  const sessionId = () => {
    try {
      return readFileSync(join(directory, ".paddock", "session"), "utf8").trim();
    } catch {
      return "";
    }
  };

  return {
    "tool.execute.before": async (input, output) => {
      ` + webBlock + `if (input.tool === "bash" && output.args && typeof output.args.command === "string") {
        const id = sessionId();
        if (id) {
          const b64 = Buffer.from(output.args.command, "utf8").toString("base64");
          output.args.command = ` + "`paddock exec ${id} --b64 ${b64}`" + `;
        }
      }
    },
  };
};
`
}
